# Generated by Django 5.2 on 2025-04-16 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Git_Gas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Git_Gas.corporation', verbose_name='Организатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Git_Gas.corporation', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен содержать цифры, символы '+' и '-'", regex='^\\+?[\\d\\-]+')], verbose_name='Телефон'),
        ),
    ]
